### ISSUE TITLE
In Safari, `NotFoundError` is thrown when svg is cached

### ISSUE THREAD

**Issue by boompttn** [shubhamjain/svg-loader#10]
This error doesn't occur in Chrome

Error message:
`NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found`

<img width="705" alt="image" src="https://user-images.githubusercontent.com/37561295/155838682-df35d197-5126-4bbf-b74f-02c3794d6fff.png">

No error if `data-cache="disabled"` is included in the svg tag

Seems to relate to https://github.com/jakearchibald/idb-keyval/issues/134

**Comment by shubhamjain** [comment]
Sorry, haven't caught with issues for some time. Are you still facing this. I wasn't able to reproduce on my safari (both mac and iOS)

**Comment by honzabilek4** [comment]
I can confirm that the issue still exists. 
I don't know exactly how this state occurs, but I was getting the same error when the `keyval-store` already existed.
It was empty and I wasn't able to run any operations on it.  It's definitely related to https://github.com/jakearchibald/idb-keyval/issues/134.
Anonymous window, or deleting the DB helped.

**Comment by shubhamjain** [comment]
Probably makes sense to solve it to cover #13 as well. If IndexedDB doesn't work, localStorage can be tried. LocalStorage has a limitation of 5MB but that should still be good enough for the cases where IndexedDB doesn't work. 

The error though shouldn't affect loading of icons. Only that caching won't work for subsequent loads.

**Comment by honzabilek4** [comment]
Well, there's something wrong with the idb indeed and it sure affects the loading of the icons. The keyval-store is sometimes stuck, not responding to any commands and the icons won't load in Safari.

Sorry that I'm not providing any more details here, but I don't know how to reproduce it yet.

<img width="989" alt="Screenshot 2022-06-01 at 11 01 32" src="https://user-images.githubusercontent.com/7890555/171368271-72dcacb3-81e3-48e2-a979-bca99125e403.png">

**Comment by honzabilek4** [comment]
Just in case you'd like to replace the storage system, I did it [here](https://github.com/shubhamjain/svg-loader/compare/main...localazy:main) with [Sfirr](https://github.com/sifrr/sifrr/tree/master/packages/browser/sifrr-storage)
It also falls back to `localStorage` and if no `localStorage` is available it falls back to the memory cache which is exactly what we needed.
Works like a charm, and I can submit a PR if you wish.

**Comment by shubhamjain** [comment]
@honzabilek4 Thanks Siffr looks good! I would appreciate the PR. But I don't think we need WebSQL Storage (a [dead API](https://caniuse.com/sql-storage)) and Cookies (bad for caching files). Although the library is tiny, I think it can be made even tinier, so we can consider including the library as a folder and remove the stuff that's not needed.

**Comment by honzabilek4** [comment]
I was thinking the same but needed to make it work quickly. It won't be difficult to it cut to the essentials and include it in the `lib` folder directly. Also, the CommonJS import is a little bit awkward. Please give me some time to get back to it, I'll submit a PR.

**Comment by shubhamjain** [comment]
@honzabilek4 Any progress on this? If not, I can initiate work on it.

**Comment by honzabilek4** [comment]
Hi, 
I'm sorry, I was on vacation 🌴 
I see that you've already implemented the `localStorage` fallback and updated the `idb-keval` library. It seems that they added [this workaround](https://github.com/jakearchibald/safari-14-idb-fix) for Safari, which should solve the issue. 
Give me a day to test it, and I suppose we can close this.

**Comment by honzabilek4** [comment]
Works fine on my end right now.
