### ISSUE TITLE
Codepen demo doesn't work for me

### ISSUE THREAD

**Issue by aderchox** [shubhamjain/svg-loader#11]
Codepen demo doesn't work for me. It's just white page and nothing more. I don't know what further information might be useful to you, but taking a look at the network tab seems that graphql requests are successful too, so it's not a network issue.

**Comment by shubhamjain** [comment]
It seems symlinks don't work properly with unpkg/npm. I have added back svg-loader.min.js here 284983a474a6d6b7b027ae3978c7d9c8666014f5. 

This has fixed the problem. 

https://codepen.io/shubhamjainco/pen/rNyBVmY
