### ISSUE TITLE
Multiple Event Attributes Not Removed

### ISSUE THREAD

**Issue by joshualyon** [shubhamjain/svg-loader#17]
If an element has multiple `onXXX` event attributes registered, the code may fail to remove all of the event attributes. 

In the current design, the code is iterating forward on the collection of attributes, but if multiple event attributes are registered and a preceding event attribute is removed, then the length of the `elem.attributes` changes each time a preceding attribute is removed.  This means that on each subsequent iteration, the loop might either skip an item (as items were reindexed) or exit early as the `i` position is outside the new length of the attribute collection. 

```javascript
for (let i = 0; i < elem.attributes.length; i++) {
     const { name, value } = elem.attributes[i];

     //Remove event functions: onmouseover, onclick ... unless specifically enabled
     if (eventNames.includes(name.toLowerCase()) && !enableJs) {
         elem.removeAttribute(name);  //<--- the elem.attributes.length gets recalculated when the attribute is removed!
         continue;
     }
     
     //etc...
}
```

A simple work around is to reverse the for loop so it starts at the end of the list of the attributes:

```javascript
for (let i = elem.attributes.length - 1; i >= 0; i--) {  //<--- only have to reverse the order
     const { name, value } = elem.attributes[i];

     //Remove event functions: onmouseover, onclick ... unless specifically enabled
     if (eventNames.includes(name.toLowerCase()) && !enableJs) {
         elem.removeAttribute(name);  //<--- even though the elem.attributes.length gets recalculated, it doesn't impact us
         //the elem.attributes.length is only referenced once to initialize `i`, and even if the actual length changes, the 
         //'lower' positioned attribute index will still exist even after its sibling is removed
         continue;
     }
     
     //etc...
}
```

As an example input case, see the attached USStates.svg from the [w3.org example SVG file listing](https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/) which has multiple event attributes registered (also attached below).

![USStates.svg](https://user-images.githubusercontent.com/966456/175657412-12613b97-832a-4c68-97c2-ded756e69c8d.svg)

**Comment by shubhamjain** [comment]
Fixed in the above PR. Instead of looping backwards, I thought storing attributes and removing them in bulk was a better approach.
