### ISSUE TITLE
Question: How to use it in Nuxt 3?

### ISSUE THREAD

**Issue by marcohofmann** [shubhamjain/svg-loader#20]
Hey!
I use your script in Nuxt 2 without any problems. In Nuxt 3 it seems not be working. Have you tried it by yourself?
THX!

**Comment by shubhamjain** [comment]
Can you please share the example snippet on something like StackBlitz? I am not familiar with Nuxt, so not sure how I go about using external JS.

**Comment by ibaGyl** [comment]
@shubhamjain @marcohofmann Did you manage to get it running? I am struggling now to find an alternative for Nuxt 3

**Comment by shubhamjain** [comment]
@ibaGyl Can you share your code?

I have it here and it seems to be working. https://stackblitz.com/edit/github-9ukebr-c6zq15?file=pages%2Findex.vue

**Comment by shubhamjain** [comment]
Closing this issue for lack of information.
