### ISSUE TITLE
Error Handling when data-src attribute is invalid

### ISSUE THREAD

**Issue by GaryBarnes17** [shubhamjain/svg-loader#22]
Hi, 

Recently, my team has been considering using this package in our React Component Library, specifically for our Icon component (which displays an svg). With this, we need to allow users to pass in the path to the svg they want to render (within our CDN). Since this is being passed in by a user, there is a chance this path (which we pass through to the `data-src` attribute) would be invalid. Currently, this error is throw, caught, and then logged to the on line 634. In order to handle this error in React, it would be helpful if this error was bubbled up so that it could be caught with an Error Boundary, and we could render a fallback component in place of the svg. Alternatively, supporting some sort of fallback component within this library could also work. Happy to talk further to explain our use case!

**Comment by shubhamjain** [comment]
Exceptions should be raised if Icons can't be fetched. Currently, it's possible to catch the error, using `window.onerror`. 

<img width="374" alt="CleanShot 2023-05-01 at 11 02 28@2x" src="https://user-images.githubusercontent.com/309760/235411579-00df72e4-8c8b-4165-ab15-8197fb4dbf91.png">
