### ISSUE TITLE
Feature request: ability to disable the observer and to inject the SVGs manually

### ISSUE THREAD

**Issue by cyberic99** [shubhamjain/svg-loader#25]
Hi,

First of all, thank you for this very useful library.
As the title says, I'd like to disable the observer, and manually inject SVGs to the DOM (using `renderIcon()` ?).
Do you think you could implement this feature ?

Thank you

**Comment by shubhamjain** [comment]
@cyberic99 Can you share an example if possible?

**Comment by cyberic99** [comment]
I'd like to do something like this:
```
<svg onload=embed_svg(this) data-src="mysvg.svg" data-cache="disabled" data-observer="disabled" />
```
so that we would not need the observer, and we would be able to call ``embed_svg()`` manually after the ``onload``

('embed_svg' is a made up name but it is a function that would embed the svg data directly in the ``svg`` tag)

Is that clear ?

Thank you

**Comment by shubhamjain** [comment]
@cyberic99 Got it! This shouldn't be too hard but what exactly is the problem you're trying to solve. Is it performance related?

**Comment by cyberic99** [comment]
> Is it performance related?

yes. although I haven't really seen a performance problem, I'd like to avoid the observer microtask if possible ;-)

**Comment by shubhamjain** [comment]
Mutation Observers are super performant and I tend to follow [YAGNI principle](https://www.techtarget.com/whatis/definition/You-arent-gonna-need-it). 

There's another library that does exactly what you're asking for (https://github.com/iconfu/svg-inject). So maybe, that's a better fit. My motivation for creating svg-loader was that I wanted something where I won't have to worry about JS more than the script tag. 

So I am gravitating towards not adding this feature unless there's a strong reason to.

**Comment by cyberic99** [comment]
thanks for your answer @shubhamjain , I totally understand
