### ISSUE TITLE
Safari first load fails with npm and cdn

### ISSUE THREAD

**Issue by iamfredrik** [shubhamjain/svg-loader#3]
First load of svg fails in a new Safari private window when library is included with npm or cdn, but not when the script is downloaded and included. All other tested browsers works either way.

Edit: loading also fails with local script if placed within head section.

**Comment by iamfredrik** [comment]
Steps to reproduce:

1. Paste the following in a new html file:

```
<html>
  <head>
    <script type="text/javascript" src="https://unpkg.com/external-svg-loader@1.3.1/svg-loader.min.js" async></script>
  </head>
  <body>
    <!-- Use an external SVG -->
    <svg data-src="https://unpkg.com/@mdi/svg@5.9.55/svg/star.svg" width="50" height="50" fill="red"></svg>
    <svg data-src="https://unpkg.com/@mdi/svg@5.9.55/svg/heart.svg" width="50" height="50" fill="red"></svg>

    <svg data-src="https://unpkg.com/@mdi/svg@5.9.55/svg/cog.svg"
        width="50"
        height="50"
        fill="currentColor"
        style="color: purple;"></svg>
  </body>
</html>

```
2. Open a new private Safari window and go to the url containing the page above.

On first load the page is blank, but when page is refreshed the icons shows up.

**Comment by shubhamjain** [comment]
Which version of Safari is this happening? I created a page with this HTML : https://shubhamjain.neocities.org/abc.html. And tried to load it in a private window and it got loaded fine.

**Comment by shubhamjain** [comment]
Okay I was able reproduce the issue on my IPhone. I'll investigate it.

**Comment by iamfredrik** [comment]
Latest versions of Safari on MacOS Big Sur and iOS/iPadOS 14.6. Seems to work on MacOS Safari Technology Preview.

**Comment by shubhamjain** [comment]
I was able to reproduce it after updating Safari. 

This is probably related to https://github.com/jakearchibald/idb-keyval/issues/120 and https://bugs.webkit.org/show_bug.cgi?id=226547

Let's wait till it gets fixed in the upstream.

**Comment by shubhamjain** [comment]
Closing this as this has been fixed upstream.
