### ISSUE TITLE
Add security policy and enable private vulnerability reporting

### ISSUE THREAD

**Issue by r00tdaemon** [shubhamjain/svg-loader#38]
Consider adding SECURITY.md and/or [Enable private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) from the security tab to allow for responsible disclosure of security issues

**Comment by shubhamjain** [comment]
I have enabled it. I am not adding SECURITY.md because this is a frontend library and attach surface is low.
