### ISSUE TITLE
Dependencies and dev dependencies

### ISSUE THREAD

**Issue by victorlacorte** [shubhamjain/svg-loader#40]
Should dependencies such as webpack and webpack-cli be listed under `dependencies`, in the package.json? I've noticed the lockfile diff due to the latest release that solves potential XSS issues.

**Comment by shubhamjain** [comment]
There was a problem with separating them since post-install didn't install dev-dependencies. 

refs: https://github.com/shubhamjain/svg-loader/issues/30

**Comment by victorlacorte** [comment]
If that's a CI issue, can't we explicitly call the build command in the GitHub Action instead of relying on the postinstall hook? This way dev dependencies won't be installed in consumers of the NPM package version of this library without need:
```sh
yarn
yarn build  # runs the same command as postinstall
yarn publish
```

(assuming running `yarn` will install both dependencies and devDependencies)

**Comment by shubhamjain** [comment]
The reason is that "main" file in `package.json` references `dist/svg-loader.min.js`, which is created using webpack.

**Comment by victorlacorte** [comment]
I don't think I fully grasped the issue yet:
- before publishing, inside the Github Action, we have access to webpack and other dev dependencies so we can correctly build in the CI. The idea is that clients don't have to install our dev dependencies as dependencies when they install `external-svg-loader`
- running the build script will generate `dist` with the minified module and the sourcemap
- the `build:cp` script will simply help on versioning the most recent minified module, but it doesn't affect publishing since the `dist` folder is being shipped to NPM. This way, we only really need `build:js` in the CI
- since `dist` is also shipped, the `main` field in the package.json will correctly resolve to the minified module

Am I missing something? Issue #30 happened since a dev dependency (`npm-run-all`) was required after installing `external-svg-loader` since the `postinstall` script was also ran; if this script is removed, this issue would be solved as well.

**Comment by shubhamjain** [comment]
Oh yes, you're right! I mistakenly assumed `dist` won't be shipped in the package itself. Yes, I think we should only need to edit the CI file to separate dependencies and devDependencies.

**Comment by victorlacorte** [comment]
Awesome! A minor improvement could also be to stop versioning the minified module, `svg-loader.min.js`, since it will be built before publishing to NPM. In this case, `npm-run-all` and `cpr` dev dependencies would also not be needed anymore

**Comment by shubhamjain** [comment]
The reason I included it is to make it handy for devs to download or copy-paste, if they want to host `svg-loader.min.js` themselves. Sure we can include link in README as well, but it's just easier to see when it's part of the repo. 

But worth considering! For now, let's just focus on this issue.

**Comment by shubhamjain** [comment]
Merged. LGTM! One problem that's happening is that sourcemap aren't getting generated. Let me look into that.

**Comment by victorlacorte** [comment]
It seems that version [1.6.1](https://www.npmjs.com/package/external-svg-loader/v/1.6.1?activeTab=code) was the last one shipped with sourcemaps in the dist folder

**Comment by victorlacorte** [comment]
@shubhamjain I'm not sure what caused the sourcemap from not being published to NPM, but a possible fix could be specifying it in the [files](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#files) field:

```json
{
  "files": [
    "./dist/svg-loader.min.js",
    "./dist/svg-loader.min.js.map"
  ]
}
```
The first array entry is redundant since it is implicitly included through the "main" field but could make sense to be included again regardless. Wdyt?

**Comment by shubhamjain** [comment]
Fixed with https://github.com/shubhamjain/svg-loader/commit/b7920683cb718cb4b5fcfa82cda51fd1344257c3. It was happening because by default npm adhered to .gitignore and it was trying to exclude the 'dist' directory. Having .npmignore fixed it.
