### ISSUE TITLE
Posibility to reinitialize script after AJAX call for example

### ISSUE THREAD

**Issue by ImKubass** [shubhamjain/svg-loader#43]
Hi!
is there a possibility to reinitialize this script after some AJAX call for example and HTML get to change.
Something like: 

``` js
SVGLoader.update()
```

**Comment by shubhamjain** [comment]
@ImKubass I didn't get you. What's the use case?

**Comment by ImKubass** [comment]
I got list of items and there is filtration or load more button ->  AJAX call that returns new items (HTML which contains svg with data-src attr) So it need to be reinitialized in order to detect new svgs

**Comment by shubhamjain** [comment]
@ImKubass you can get reference to the element and call `.setAttribute('data-src', newSrc)` on it, then the new icon should be loaded. SVG-loader uses Mutation observers to detect attribute change. If this is not happening, please attach a snippet of your code and I will look into it.

**Comment by ImKubass** [comment]
@shubhamjain 
Sorry my mistake, it loads even new svg thats added dynamicly. So its no need to reinit script.
