### ISSUE TITLE
In `yarn test`, ReferenceError: IntersectionObserver is not defined

### ISSUE THREAD

**Issue by okbytes** [shubhamjain/svg-loader#6]
My tests are failing and I'm not sure how to fix it. I'm using Typescript and React if that helps. I'm new to testing, so it's all still quite confusing. Ideally, I could just mock the thing globally as I don't want to import it all over the place, though I'm not sure how.

```jsx
Test suite failed to run

    ReferenceError: IntersectionObserver is not defined

      1 | import { IconNames } from "../utils/icon-names";
      2 |
    > 3 | import "external-svg-loader";
        | ^
      4 |
      5 | type Props = {
      6 |   name: IconNames;

      at Object.<anonymous> (node_modules/external-svg-loader/svg-loader.js:245:21)
```

**Comment by shubhamjain** [comment]
svg-loader uses IntersectionObserver API, which is supported by almost all browsers. Typescript is likely complaining because it encountered a global name it doesn't anything about.

I have to check best way to fix this, since my knowledge about typescript is a bit rusty.

**Comment by okbytes** [comment]
Oops. I wasn't clear enough. My bad. This is related to running `yarn test` using Jest. The _actual_ code runs, it's just all tests fail (and thus all my deploys fail). Maybe a section for how to mock this to avoid the tests from busting?

**Comment by shubhamjain** [comment]
Oh I see. I am guessing the problem is that the code tries to execute IntersectionObserver which Jest doesn't have access to. Perhaps, best way to resolve this would be to check if the API exists and only then run the code. This also handles the case where API is not supported on the browser.

**Comment by radenpioneer** [comment]
i got similar error, when i hover to `import 'external-svg-loader'` in VSCode:

```
Could not find a declaration file for module 'external-svg-loader'. '/home/fossa/projects/client/dpcmbk/frontend/node_modules/external-svg-loader/svg-loader.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/external-svg-loader` if it exists or add a new declaration (.d.ts) file containing `declare module 'external-svg-loader';`ts(7016)
```

I use Typescript in a Next.JS project (which also uses React).

**Comment by shubhamjain** [comment]
I have added some code that would make this executable in node. Since, there is no API to be used, there's no type declaration needed. I added an empty *.d.ts file to ensure that warning isn't thrown.
