### ISSUE TITLE
`this` has been rewritten to `undefined`

### ISSUE THREAD

**Issue by samedro** [shubhamjain/svg-loader#8]
In arrow function `const renderIcon = async (elem) => {`, rollup throws a warning about `this` being undefined.
```
  const renderBodyCb = 
.bind(this, elem, { enableJs, disableUniqueIds, disableCssScoping });
```
 It is indeed never defined because of the context in arrow functions, which does not exist.

**Comment by shubhamjain** [comment]
`this` is never used in that function. Yes, arrow functions bind to the current context with undefined in this case, but for me, it's just convenient syntax to define a function.
